# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-26 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(max_length=100)),
                ('your_email', models.EmailField(max_length=254)),
                ('your_subject', models.CharField(max_length=100)),
                ('your_comment', models.TextField(max_length=200)),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
